
use_frameworks!

target 'CountryPickerViewDemo' do 
  platform :ios, '8.0'
  pod 'CountryPickerView', :path => '../'  
end

target 'CountryPickerViewTVDemo' do
  platform :tvos, '10.0'
  pod 'CountryPickerView', :path => '../'  

end
